Repository TexasDigitalLibrary/Vireo, pull requests merged in 2018-06, with the labels that each got.

#882 Ref #875: ORCID API has changed, requiring updated validation code
  src/main/java/org/tdl/vireo/utility/OrcidUtility.java
Labels: approved, review

#926 Using approveEmbargoDate instead of approveEmbargo
  src/main/resources/submission_list_columns/SYSTEM_Default_Submission_List_Columns.json
Labels: approved

#927 Added placeholder text
  src/main/webapp/app/views/admin/info/edit/input-contact.html
Labels: approved

#928 Allow null values to designate unassignment
  src/main/java/org/tdl/vireo/controller/SubmissionController.java
  src/main/webapp/app/model/submission.js
Labels: approved

#929 fixed input focus for license input types
  src/main/webapp/app/directives/fieldProfileFocusDirective.js
Labels: approved

#930 added orderby to sort admin view all files table by date
  src/main/webapp/app/views/admin/view.html
Labels: approved

#931 modified assigned to field display in list view to show name
  src/main/webapp/app/controllers/submission/submissionListController.js
Labels: approved

#932 fixed typo, modified gloss, and converted add filter booleans to strings
  src/main/webapp/app/controllers/submission/submissionListController.js
  src/main/webapp/app/views/sideboxes/furtherFilterBy/furtherFilterBy.html
  src/main/webapp/app/views/sideboxes/furtherFilterBy/furtherFilterByUmiPublication.html
Labels: approved

#934 "Last event" column does not work in List View
  src/main/java/org/tdl/vireo/model/Submission.java
  src/main/java/org/tdl/vireo/model/repo/impl/SubmissionRepoImpl.java
  src/main/resources/submission_list_columns/SYSTEM_Default_Submission_List_Columns.json
Labels: approved

#936 Modified view to show alternate embargo options
  src/main/webapp/app/views/directives/reviewSubmissionFields.html
Labels: approved

#937 Remove "Submission Type" and "Degree Date" from default list for cust…
  src/main/resources/submission_list_columns/SYSTEM_Default_Submission_List_Column_Titles.json
Labels: approved

#938 Controlled Vocabulary editing always resets table
  src/main/webapp/app/controllers/settings/controlledVocabularyRepoController.js
Labels: approved

#883 added functionality to filter individual susbmissions from admin subm…
  src/main/java/org/tdl/vireo/model/repo/impl/SubmissionRepoImpl.java
  src/main/resources/submission_list_columns/SYSTEM_Default_Submission_List_Columns.json
  src/main/webapp/app/controllers/submission/submissionListController.js
  src/main/webapp/app/resources/styles/sass/app.scss
  src/main/webapp/app/views/admin/list.html
Labels: approved

#906 4.0.x 900 list view display 1000
  src/main/webapp/app/controllers/submission/submissionListController.js
Labels: approved

#933 now using exact match filter for submission type
  src/main/webapp/app/views/sideboxes/furtherFilterBy/furtherFilterBy.html
  src/main/webapp/app/views/sideboxes/furtherFilterBy/furtherFilterBySubmissionType.html
Labels: approved

#940 June sprint #756 duplicate dom ids
  package-lock.json
  package.json
  src/main/java/org/tdl/vireo/auth/controller/AuthController.java
  src/main/webapp/app/directives/validatedInputDirective.js
  src/main/webapp/app/views/admin/settings/application/organizationSettings.html
  src/main/webapp/app/views/admin/settings/application/proquestUmiDegreeCodeSettings.html
  src/main/webapp/app/views/admin/settings/application/shibbolethAttributes.html
  src/main/webapp/app/views/admin/settings/application/submissionAvailability.html
  src/main/webapp/app/views/admin/settings/organization/manageOrganization.html
  src/main/webapp/app/views/admin/settings/organization/workflowsteps/workflowStepContent.html
  src/main/webapp/app/views/admin/settings/workflow/fieldGlosses.html
  src/main/webapp/app/views/directives/validatedInput.html
  src/main/webapp/app/views/modals/loginModal.html
  src/main/webapp/app/views/modals/organization/emailWorkflowRuleCreate.html
  src/main/webapp/app/views/modals/organization/emailWorkflowRuleDelete.html
  src/main/webapp/app/views/modals/organization/emailWorkflowRuleEdit.html
  src/main/webapp/app/views/modals/organization/fieldprofiles/fieldProfilesConfirmRemoveModal.html
  src/main/webapp/app/views/modals/organization/fieldprofiles/fieldProfilesEditModal.html
  src/main/webapp/app/views/modals/organization/fieldprofiles/fieldProfilesNewModal.html
  src/main/webapp/app/views/modals/organization/notesConfirmRemoveModal.html
  src/main/webapp/app/views/modals/organization/notesEditModal.html
  src/main/webapp/app/views/modals/organization/notesNewModal.html
  src/main/webapp/app/views/modals/organization/organizationConfirmDeleteModal.html
  src/main/webapp/app/views/modals/organization/organizationConfirmRestoreDefaultsModal.html
  src/main/webapp/app/views/modals/organization/workflowStepCreateModal.html
  src/main/webapp/app/views/modals/organization/workflowStepDeleteModal.html
  src/main/webapp/app/views/modals/settings/controlledVocabularyEditModal.html
  src/main/webapp/app/views/modals/settings/controlledVocabularyNewModal.html
  src/main/webapp/app/views/modals/settings/customActionEditModal.html
  src/main/webapp/app/views/modals/settings/customActionNewModal.html
  src/main/webapp/app/views/modals/settings/degreeEditModal.html
  src/main/webapp/app/views/modals/settings/degreeNewModal.html
  src/main/webapp/app/views/modals/settings/depositLocationEditModal.html
  src/main/webapp/app/views/modals/settings/depositLocationNewModal.html
  src/main/webapp/app/views/modals/settings/documentTypesEditModal.html
  src/main/webapp/app/views/modals/settings/documentTypesNewModal.html
  src/main/webapp/app/views/modals/settings/emailTemplatesEditModal.html
  src/main/webapp/app/views/modals/settings/emailTemplatesNewModal.html
  src/main/webapp/app/views/modals/settings/embargoEditModal.html
  src/main/webapp/app/views/modals/settings/embargoNewModal.html
  src/main/webapp/app/views/modals/settings/graduationMonthEditModal.html
  src/main/webapp/app/views/modals/settings/graduationMonthNewModal.html
  src/main/webapp/app/views/modals/settings/languagesEditModal.html
  src/main/webapp/app/views/modals/settings/languagesNewModal.html
  src/main/webapp/app/views/modals/settings/organizationCategoryEditModal.html
  src/main/webapp/app/views/modals/settings/organizationCategoryNewModal.html
  src/main/webapp/app/views/modals/verifyEmailModal.html
  src/main/webapp/app/views/modals/view/editFileModal.html
  src/main/webapp/app/views/modals/workflow/fieldGlossConfirmRemoveModal.html
  src/main/webapp/app/views/modals/workflow/fieldGlossNewModal.html
  src/main/webapp/app/views/modals/workflow/fieldGlosssEditModal.html
  src/main/webapp/app/views/modals/workflow/fieldPredicateConfirmRemoveModal.html
  src/main/webapp/app/views/modals/workflow/fieldPredicateNewModal.html
  src/main/webapp/app/views/modals/workflow/fieldPredicatesEditModal.html
  src/main/webapp/app/views/register.html
  src/main/webapp/app/views/sideboxes/organization.html
  src/test/java/org/tdl/vireo/controller/AuthControllerTest.java
  src/test/java/org/tdl/vireo/integration/AuthIntegrationTest.java
Labels: approved

#943 Implemented a display for custom actions in list view
  src/main/java/org/tdl/vireo/model/CustomActionValue.java
  src/main/java/org/tdl/vireo/model/Submission.java
  src/main/webapp/app/controllers/submission/submissionListController.js
  src/main/webapp/app/views/admin/list.html
Labels: approved

#945 Use correct functions when closing assignee and reset working state w…
  src/main/webapp/app/controllers/submission/adminSubmissionViewController.js
  src/main/webapp/app/views/modals/view/assign.html
Labels: approved

#948 June sprint #860 add comment email templates
  src/main/java/org/tdl/vireo/utility/OrcidUtility.java
  src/main/webapp/app/controllers/submission/adminSubmissionViewController.js
Labels: approved

#951 June sprint #862 tab order
  src/main/webapp/app/resources/styles/sass/directives/_all.scss
  src/main/webapp/app/resources/styles/sass/directives/_validatedSelect.scss
  src/main/webapp/app/resources/styles/sass/views/submission/_student-submission.scss
  src/main/webapp/app/views/directives/dropZone.html
  src/main/webapp/app/views/inputtype/input-select.html
  src/main/webapp/app/views/submission/submission.html
Labels: approved

#957 June sprint #861 custom action persistence
  src/main/java/org/tdl/vireo/controller/SubmissionController.java
  src/main/webapp/app/config/apiMapping.js
  src/main/webapp/app/model/submission.js
Labels: approved

#944 changed corrections completed button to match vireo 3
  src/main/webapp/app/directives/submissionDialogDirective.js
  src/main/webapp/app/views/directives/submissionDialog-state.html
Labels: approved

#946 Displaying advisor email on committee contact email
  src/main/java/org/tdl/vireo/model/Submission.java
  src/main/resources/submission_list_columns/SYSTEM_Default_Submission_List_Columns.json
Labels: approved

#947 added email addresses to action logs for sent emails
  src/main/java/org/tdl/vireo/controller/SubmissionController.java
Labels: approved

#941 Add Return email recipients in Add File on submission
  src/main/webapp/app/views/modals/view/addFileModal.html
Labels: approved

#960 Long filenames in uploaded file overflow out of sidebox
  src/main/webapp/app/resources/styles/sass/app.scss
Labels: approved

#952 Validate over an array of values when using pattern validation types,…
  pom.xml
  src/main/java/org/tdl/vireo/model/InputType.java
  src/main/java/org/tdl/vireo/model/Validation.java
  src/main/java/org/tdl/vireo/model/validation/FieldValueValidator.java
  src/main/resources/input_types/SYSTEM_Input_Types.json
  src/main/webapp/app/model/submission.js
Labels: approved

#962 Updating weaver ui core to 2.0.0-RC4
  package-lock.json
  package.json
Labels: approved

#942 June sprint #897 assigned to unassigned
  src/main/java/org/tdl/vireo/controller/SubmissionListController.java
  src/main/java/org/tdl/vireo/model/repo/impl/SubmissionRepoImpl.java
  src/main/webapp/app/controllers/submission/submissionListController.js
Labels: review

#967 added regex to validate email addresses in add file modal
  src/main/webapp/app/controllers/submission/adminSubmissionViewController.js
  src/main/webapp/app/views/modals/view/addFileModal.html
Labels: approved

#968 Handle case where filterValue may be null when .toString() is used
  src/main/webapp/app/controllers/submission/submissionListController.js
Labels: approved

#971 Improve tab selection display of workflow step navigation buttons
  src/main/webapp/app/resources/styles/sass/views/submission/_student-submission.scss
Labels: approved

#972 fixing problem with logical operator evaluation implemented in previo…
  src/main/webapp/app/controllers/submission/adminSubmissionViewController.js
Labels: approved
